# Generated by Django 5.0.7 on 2024-07-27 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resources', models.CharField(max_length=1000)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='tracks.track')),
            ],
        ),
    ]
