# Generated by Django 5.0.7 on 2024-07-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_resources_slug_track_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resources',
            options={'verbose_name_plural': 'Resources'},
        ),
        migrations.RemoveField(
            model_name='track',
            name='enddate',
        ),
    ]
