# Generated by Django 5.0.7 on 2024-07-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_alter_resources_options_remove_track_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resources',
            name='resources',
            field=models.URLField(),
        ),
    ]
