# Generated by Django 5.0.7 on 2024-07-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customusermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
