# Generated by Django 5.0.7 on 2024-07-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customusermodel_first_name_customusermodel_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
