# Generated by Django 5.0.7 on 2024-07-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customusermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
