# Generated by Django 5.0.7 on 2024-07-27 10:32

import accounts.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customusermodel_github_customusermodel_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/user', validators=[accounts.validation.validate_file_extention]),
        ),
    ]
