# Generated by Django 5.0.7 on 2024-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_date',
            field=models.DateField(),
        ),
    ]
