# Generated by Django 5.0.7 on 2024-07-25 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_job_slug_recruiter_slug_skills_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.recruiter'),
        ),
    ]
