# Generated by Django 5.0.7 on 2024-07-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_job_user_recruiter_user_skills_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='recruiters_email',
            field=models.CharField(max_length=254),
        ),
    ]
