# Generated by Django 5.0.7 on 2024-07-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_recruiter_recruiters_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='recruiters_email',
            field=models.EmailField(max_length=254),
        ),
    ]
