# Generated by Django 5.0.7 on 2024-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_recruiter_recruiters_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Replied', 'Replied'), ('Hanging', 'Hanging'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
