# Generated by Django 5.0.7 on 2024-07-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Replied', 'Replied'), ('Ghosted', 'Ghosted'), ('Accepted', 'Accepted')], default='Pending', max_length=10),
        ),
    ]
